### ISSUE TITLE
Run scripts on full datasets to identify possible bugs

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#52]

**Comment by Nate-Wessel** [comment]
Has this been tried yet?

**Comment by felipevh** [comment]
Yes, 2016 is pretty good, just two users data is so bad it crashes the kde.
2017 is pretty bad, some kde crashes, some weird timestamp stuff I'm still
working on

**Comment by Nate-Wessel** [comment]
What are the issues exactly? Too many points? Points outside the projection area?

**Comment by felipevh** [comment]
in 2016 its weird: proportions don't sum to 1? If you run etc/remove.py on the 2016 coordinates you'll get a coordinates file with 2 users, both generate the error.

in 2017 there are some with the same bug, others that have a time difference of 0 somehow (same timestamp ostensibly, but different locations) causing a 0 division error. I'm still working on that one.

**Comment by sfarber111** [comment]
Was this due to home/work/school locations overlapping?

Please specify, what is 2016 data and 2017 data? I think I only know about 2017.

Steve

On Jul 13, 2018, at 1:40 PM, Felipe Vicencio-Heap <notifications@github.com<mailto:notifications@github.com>> wrote:


in 2016 its weird: proportions don't sum to 1? If you run etc/remove.py on the 2016 coordinates you'll get a coordinates file with 2 users, both generate the error.

in 2017 there are some with the same bug, others that have a time difference of 0 somehow (same timestamp ostensibly, but different locations) causing a 0 division error. I'm still working on that one.

**Comment by felipevh** [comment]
I don't think so, for 2016 it looked like garbage input data. Out of 130 points, there were 4 unique ones, with one point repeated 127 times. My guess is a floating point error caused by a really high peak in the kde made the probabilities sum not equal to 1

Also I don't have the tower data (I think) I only have 2016 and 2017 CFS data

**Comment by felipevh** [comment]
Closing this for 2 distinct issues
